### ISSUE TITLE
mintapi.api.MintException: Could not parse response to set_user_property

### ISSUE THREAD

**Issue by zosocanuck** [mrooney/mintapi#117]
Well, everything was working yesterday, however this morning I am now getting this error:

```
[11088:6688:0924/092002.625:ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_plugin from binding interface: memory_instrumentation::mojom::Coordinator exposed by: content_browser
Traceback (most recent call last):
  File "overunder.py", line 35, in <module>
    result = mint.get_transactions_json(include_investment=False, skip_duplicates=False, start_date=datetime.datetime.now().strftime('%m/01/%y'))
  File "C:\Python27\lib\site-packages\mintapi\api.py", line 316, in get_transactions_json
    self.set_user_property('hide_duplicates', 'T' if skip_duplicates else 'F')
  File "C:\Python27\lib\site-packages\mintapi\api.py", line 286, in set_user_property
    raise MintException("Could not parse response to set_user_property")
mintapi.api.MintException: Could not parse response to set_user_property
```

**Comment by GraemeCrawley** [comment]
I'm having the same issue. 

`Traceback (most recent call last):
  File "jsonParser.py", line 82, in <module>
    transactions = mint.get_transactions_json()
  File "/usr/local/lib/python2.7/dist-packages/mintapi/api.py", line 303, in get_transactions_json
    self.set_user_property('hide_duplicates', 'T' if skip_duplicates else 'F')
  File "/usr/local/lib/python2.7/dist-packages/mintapi/api.py", line 273, in set_user_property
    raise MintException("Could not parse response to set_user_property")
mintapi.api.MintException: Could not parse response to set_user_property
`

**Comment by wdbdesign** [comment]
Has anyone solved this issue?  It started hitting me 7 days ago, and I haven't been able to figure out what's causing it.  Thanks!

**Comment by atitkothari** [comment]
I am getting the same error. Did anyone get a fix for it yet?

**Comment by ccarrollATjhuecon** [comment]
Mint must have changed the way this option is set, breaking the code.  A very crude and temporary fix is just to comment out the line 

self.set_user_property('hide_duplicates', 'T' if skip_duplicates else 'F')
 
in api.py

**Comment by mrooney** [comment]
Just merged into master a different approach; now chromedriver + selenium is used for all requests. Give it a shot!
