### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Jikodis** [mrooney/mintapi#151]
To preface this, I am on Windows, so the issues might simply be that. I installed mintapi and selenium successfully, and I have installed chromedriver at c:\windows as mentioned here: https://stackoverflow.com/questions/33150351/how-do-i-install-chromedriver-on-windows-10-and-run-selenium-tests-with-chrome

When I enter my credentials, I get the following output:

```
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python37\Scripts\mintapi-script.py", line 11, in <module>
    load_entry_point('mintapi==1.30', 'console_scripts', 'mintapi')()
  File "c:\users\*****\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 823, in main
    headless=options.headless)
  File "c:\users\*****\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 203, in create
    return Mint(email, password, **opts)
  File "c:\users\*****\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 199, in __init__
    headless=headless)
  File "c:\users\*****\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 265, in login_and_get_token
    headless=headless)
  File "c:\users\*****\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 81, in get_web_driver
    zip_file = zipfile.ZipFile(io.BytesIO(request.content))
  File "c:\users\*****\appdata\local\programs\python\python37\lib\zipfile.py", line 1200, in __init__
    self._RealGetContents()
  File "c:\users\*****\appdata\local\programs\python\python37\lib\zipfile.py", line 1267, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Is there a way to remedy this error, or is simply doing this in Linux or Mac the option?

**Comment by mrooney** [comment]
Thanks for the info, I'll post in #150 / #135 and see if anyone has any yays or nays for Windows.

**Comment by eschizoid** [comment]
@mrooney https://github.com/mrooney/mintapi/pull/152

**Comment by mrooney** [comment]
Thanks, just released this as 1.31 thanks to @eschizoid , @Jikodis can you give it a shot and let me know if it works? :)

**Comment by Jikodis** [comment]
@mrooney I ran `pip uninstall mintapi` then `pip install mintapi`. It stated I had version 1.31 now. I then ran `mintapi --budgets` and provided my e-mail and stored password. I received the error below. Let me know if I am not following any installation steps properly. I do have chromedriver.exe stored at `c:\windows`

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Scripts\mintapi-script.py", line 11, in <module>
    load_entry_point('mintapi==1.31', 'console_scripts', 'mintapi')()
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 823, in main
    headless=options.headless)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 203, in create
    return Mint(email, password, **opts)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 199, in __init__
    headless=headless)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 265, in login_and_get_token
    headless=headless)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\mintapi\api.py", line 81, in get_web_driver
    zip_file = zipfile.ZipFile(io.BytesIO(request.content))
  File "c:\users\user\appdata\local\programs\python\python37\lib\zipfile.py", line 1200, in __init__
    self._RealGetContents()
  File "c:\users\user\appdata\local\programs\python\python37\lib\zipfile.py", line 1267, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by eschizoid** [comment]
@Jikodis can you see what type of file was downloaded and share the path as well as the name of the file?

Unfortunately is a little bit difficult to reproduce the error without a windows environment.

**Comment by lzednik** [comment]
Hi, I seem to have the same issue. Has there been a resolution?

**Comment by spencer-scott** [comment]
Hello, I am also having this issue in a windows VM environment.

**Comment by eschizoid** [comment]
@lzednik or @spencer-scott could you please try out this branch?

https://github.com/eschizoid/mintapi/tree/bugfix/windows-zip

Unfortunately I don't have a windows machine and it's hard for me to test :(

I think I know what the problem is, so hopefully, this branch will take care of it.
