### ISSUE TITLE
Chrome failed to start: exited abnormally - WebDriverException

### ISSUE THREAD

**Issue by sukhvinder1** [mrooney/mintapi#188]
Mint e-mail: my-email-address
Mint password: 
Traceback (most recent call last):
  File "api.py", line 1237, in <module>
    main()
  File "api.py", line 1164, in main
    wait_for_sync_timeout=options.wait_for_sync_timeout
  File "api.py", line 366, in create
    return Mint(email, password, **opts)
  File "api.py", line 362, in __init__
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "api.py", line 450, in login_and_get_token
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "api.py", line 216, in get_web_driver
    driver = Chrome(chrome_options=chrome_options, executable_path="%s" % executable_path)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-54-generic x86_64)

**Comment by sukhvinder1** [comment]
Nevermind. Running it headless solved the problem. 
Awesome App. Made my life so easy. 
Thanks @mrooney
