### ISSUE TITLE
MintAPI doesn't work in RaspberryPi

### ISSUE THREAD

**Issue by pisakhov** [mrooney/mintapi#212]
Thank you for sharing this amazing tool.
It works for me in Windows, but when I try to use it in RaspberryPi it gives me this message:

`pi@raspberrypi:~/Desktop/mintapi $ sudo python3 mint.py
Traceback (most recent call last):
  File "mint.py", line 15, in <module>
    wait_for_sync_timeout=10,
  File "/home/pi/Desktop/mintapi/mintapi/api.py", line 373, in __init__
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "/home/pi/Desktop/mintapi/mintapi/api.py", line 461, in login_and_get_token
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "/home/pi/Desktop/mintapi/mintapi/api.py", line 216, in get_web_driver
    driver = Chrome(chrome_options=chrome_options, executable_path="%s" % executable_path)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/Desktop/mintapi/chromedriver'
`

**Comment by mrooney** [comment]
I believe #167 is a good issue to discuss this in where some folks may have gotten it working!
