### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'NA'

### ISSUE THREAD

**Issue by agt24** [mrooney/mintapi#213]
Any suggestions on what is causing this error?
```bash
(py3.5) $ mintapi -t --filename mint_transactions_from_mintapi_2020-05-11.json --no_wait_for_sync email@email.com

Traceback (most recent call last):
  File "/Users/adamt/miniconda3/envs/py3.5/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/Users/adamt/miniconda3/envs/py3.5/lib/python3.5/site-packages/mintapi/api.py", line 1287, in main
    include_investment=options.include_investment)
  File "/Users/adamt/miniconda3/envs/py3.5/lib/python3.5/site-packages/mintapi/api.py", line 708, in get_transactions
    .replace('uncategorized', pd.NA))
AttributeError: module 'pandas' has no attribute 'NA'

```

**Comment by agt24** [comment]
rebuilt my conda environment with python 3.7 and that seems to have fixed it.

**Comment by agt24** [comment]
rebuilt my conda environment with python 3.7 and that seems to have fixed it.
