### ISSUE TITLE
Error in atexit._run_exitfuncs:

### ISSUE THREAD

**Issue by j450h1** [mrooney/mintapi#217]
I enter this in the terminal: ```mintapi --keyring --headless {you@example.com}```

I then enter my password when prompted and the correct MFA. Then I see a JSON response of my accounts, but at the very bottom this error appears. Is everything fine and this is just a red herring?

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/jas/miniconda3/lib/python3.7/site-packages/mintapi/api.py", line 476, in close
    self.driver.find_element_by_id('link-logout').click()
  File "/Users/jas/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/jas/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/jas/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/jas/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a id="link-logout" class="navbar-link" href="/logout.event?task=explicit&amp;country=">...</a> is not clickable at point (704, 32). Other element would receive the click: <div data-automation-id="ModalDialog--container" open="" role="dialog" class="StyledModalDialog__Container-cn89yw-1 iIlfZT" style="z-index: 102;">...</div>
  (Session info: headless chrome=83.0.4103.116)

```

**Comment by mrooney** [comment]
Should be fixed in master after merging #221, thanks for the report!
