### ISSUE TITLE
Extended transactions started failing overnight.

### ISSUE THREAD

**Issue by dragonfax** [mrooney/mintapi#243]
```
Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'odate'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "./home/seluser/.local/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 1386, in main
    data = mint.get_detailed_transactions(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 734, in get_detailed_transactions
    df['odate'] = df['odate'].apply(json_date_to_datetime)
  File "/home/seluser/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/seluser/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'odate'
```

**Comment by dragonfax** [comment]
The issue disappeared over night as well. So it must be the result of a particular transaction in my account in a particular state. Closing because I can't recreate this issue.
