### ISSUE TITLE
"selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable" error

### ISSUE THREAD

**Issue by CodingPenguin** [mrooney/mintapi#265]
Here is the whole error that shows up when I run the default code on the README. I'm certain it must be super simple and I'm not seeing it.
`
Traceback (most recent call last):
  File "/Users/codingdanny/projects/python/mint/index.py", line 2, in <module>
    mint = mintapi.Mint(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mintapi/api.py", line 515, in __init__
    self.login_and_get_token(email, password,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mintapi/api.py", line 603, in login_and_get_token
    self.driver, self.status_message = get_web_driver(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mintapi/api.py", line 434, in get_web_driver
    _sign_in(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, imap_account,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mintapi/api.py", line 410, in _sign_in
    driver.find_element_by_id("ius-sign-in-mfa-password-collection-current-password").send_keys(password)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=91.0.4472.114)
`

**Comment by jaron-l** [comment]
@CodingPenguin Do you have a method to reproduce?

**Comment by mrooney** [comment]
Closed via #270
