### ISSUE TITLE
CI: SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by jaron-l** [mrooney/mintapi#267]
This is to track the build errors that travis-ci is having with SyntaxError showing up in the build errors associated with pandas.

The error as it appears on Job [#422.1](https://travis-ci.org/github/mrooney/mintapi/jobs/774557271#L163):
```
$ nosetests
E
======================================================================
ERROR: Failure: SyntaxError (future feature annotations is not defined (_decorators.py, line 1))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/mrooney/mintapi/mintapi/__init__.py", line 1, in <module>
    from .api import Mint
  File "/home/travis/build/mrooney/mintapi/mintapi/api.py", line 36, in <module>
    import pandas as pd
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas-1.3.0rc1-py3.6-linux-x86_64.egg/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas-1.3.0rc1-py3.6-linux-x86_64.egg/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas-1.3.0rc1-py3.6-linux-x86_64.egg/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas-1.3.0rc1-py3.6-linux-x86_64.egg/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas-1.3.0rc1-py3.6-linux-x86_64.egg/pandas/util/_decorators.py", line 1
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
----------------------------------------------------------------------
Ran 1 test in 0.436s
FAILED (errors=1)
The command "nosetests" exited with 1.
Done. Your build exited with 1.
```

**Comment by jaron-l** [comment]
In my digging about trying to recreate the travis ci build environment, I ran into several questions that hopefully @mrooney can help me out with.

1. In the [.travis.yml](https://github.com/mrooney/mintapi/blob/e8df28240df7f8283449ba149dc0ba6f325867e9/.travis.yml#L7) on line 7, I see that we don't install pinned packages. Is there a reason for this? Normally I would recommend that this should be `pip install -r requirements.txt nose` as it makes the packages in the environment more deterministic. As it is, I'm struggling to verify that I am recreating the exact same build environment as the travis-ci one as I don't know what is in their build environment as they don't publish their container images as far as I can tell. When I use the build environment this way, my tests succeed.
2. Why do we build the packages at all? [As shown in line 8 of the same file](https://github.com/mrooney/mintapi/blob/e8df28240df7f8283449ba149dc0ba6f325867e9/.travis.yml#L8), we run setup.py but that package is never used. Is it just to verify that it can be built?

I can turn this into a pull request to demonstrate what I'm talking about but I thought I'd ask my questions first in case I'm missing something.

**Comment by mrooney** [comment]
Thanks so much for the research! I don't think you are missing anything, if
it makes more sense to work a different way now, let's definitely give it a
shot :)
