### ISSUE TITLE
headless chrome in AWS Linux 2

### ISSUE THREAD

**Issue by pisakhov** [mrooney/mintapi#273]
I noticed the update of soft-token. However, my session is saved from before.
This is the error I'm getting.

```
[ec2-user@ip-172-31-18-118 ~]$ sudo python3 index.py
Traceback (most recent call last):
  File "index.py", line 21, in <module>
    session_path='/home/ec2-user/mintsession',  # Directory that the Chrome persistent session will be written/read from.
  File "/usr/local/lib/python3.7/site-packages/mintapi/api.py", line 529, in __init__
    chromedriver_download_path=chromedriver_download_path)
  File "/usr/local/lib/python3.7/site-packages/mintapi/api.py", line 618, in login_and_get_token
    chromedriver_download_path=chromedriver_download_path)
  File "/usr/local/lib/python3.7/site-packages/mintapi/api.py", line 435, in get_web_driver
    imap_password, imap_server, imap_folder)
  File "/usr/local/lib/python3.7/site-packages/mintapi/api.py", line 410, in _sign_in
    driver.find_element_by_id("ius-sign-in-mfa-password-collection-current-password").send_keys(password)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=92.0.4515.131)
```

I'm using AWS Linux 2.

Thank you

**Comment by mrooney** [comment]
What is index.py? This is not a file in the mintapi repository :)

**Comment by pisakhov** [comment]
no, this is the script to run the program.

```
import mintapi
import datetime
import json
import os

os.system("sudo pkill -f /home/ec2-user/chromedriver")
os.system("sudo pkill -f /opt/google/chrome/chrome")

mint = mintapi.Mint(
        'xxxxx',  # Email used to log in to Mint
        'xxxxx',  # Your password used to log in to mint
        # Optional parameters
        mfa_method='sms',  # Can be 'sms' (default) or 'email'.
        # if mintapi detects an MFA request, it will trigger the requested method
        # and prompt on the command line.
        headless=True,  # Whether the chromedriver should work without opening a
        # visible window (useful for server-side deployments)
        mfa_input_callback=None,  # A callback accepting a single argument (the prompt)
        # which returns the user-inputted 2FA code. By default
        # the default Python `input` function is used.
        session_path='/home/ec2-user/mintsession',  # Directory that the Chrome persistent session will be written/read from.
        # To avoid the 2FA code being asked for multiple times, you can either set
        # this parameter or log in by hand in Chrome under the same user this runs
        # as.
        #imap_account='xxxxx',  # account name used to log in to your IMAP server
        #imap_password=None,  # account password used to log in to your IMAP server
        #imap_server='imap.gmail.com',  # IMAP server host name
        #imap_folder='INBOX',  # IMAP folder that receives MFA email
        #wait_for_sync=True,  # do not wait for accounts to sync
        #wait_for_sync_timeout=30,  # number of seconds to wait for sync
)


budgetw=mint.get_budgets()
#print(budgetw)

data = {}
data['bud'] = []
for i in budgetw['spend']:
        #print(i['cat'])
        #print(i['amt'])
        data['bud'].append({
                'cat': i['cat'],
                'amt': i['amt'],
                'datenow': str(datetime.datetime.now())
    })

with open('/home/ec2-user/data.txt', 'w') as outfile:
        json.dump(data, outfile)

data = {}
data['accw'] = []
accw=mint.get_accounts()
for i in accw:
        data['accw'].append({
                'account_mintid': i['id'],
                'account_nickname': i['accountName'],
                'account_name': i['yodleeName'],
                'account_fourdigits': i['yodleeAccountNumberLast4'],
                'account_type': i['accountType'],
                'account_value': i['value'],
                'account_lastupdate': str(i['lastUpdatedInDate']),
                'account_status': i['status'],
                'account_isclosed': i['isClosed']
        })

with open('/home/ec2-user/json_accounts.txt', 'w') as outfile:
        json.dump(data, outfile)


##06/01/20##
first_month = datetime.datetime.now()
first_month = first_month.strftime("%m/01/%y")
##2020-06##
file_month = datetime.datetime.now()
file_month = file_month.strftime("%Y-%m")

transactions = mint.get_transactions_json(include_investment=False, skip_duplicates=False, start_date = first_month)

with open('/home/ec2-user/transactions/'+ file_month +'.txt', 'w') as outfile:
        json.dump(transactions, outfile)

#print(transactions)

bills = mint.get_bills()
print(bills)

os.system("sudo pkill -f /home/ec2-user/chromedriver")
os.system("sudo pkill -f /opt/google/chrome/chrome")



mint.close()

```
index.py


sorry for the bad syntax.

versions:
`Google Chrome 92.0.4515.131
ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310})
`

**Comment by pisakhov** [comment]
I opened Lightsail's instance with ubuntu 20, and I reinstall everything.
I removed the two-step-verification
I use mfa_method='sms'

I think the mfa_method='soft-token' method must be with more explanation in the read me file..


Is it possible for the next version of mintapi, to have an option to select which browser to use?

Thank you for your quick response..
