### ISSUE TITLE
Transactions Error?

### ISSUE THREAD

**Issue by teamcoltra** [mrooney/mintapi#40]
This is what I get when I try to get transactions (both command line and in the code)
```
Traviss-MacBook-Pro:mintest teamcoltra$ mintapi --transactions
Mint e-mail: notmyeamil@email.com
Mint password: 
Traceback (most recent call last):
  File "/usr/local/bin/mintapi", line 9, in <module>
    load_entry_point('mintapi==1.9', 'console_scripts', 'mintapi')()
  File "/Library/Python/2.7/site-packages/mintapi/api.py", line 434, in main
    data = mint.get_transactions()
  File "/Library/Python/2.7/site-packages/mintapi/api.py", line 149, in get_transactions
    raise ImportError('transactions data requires pandas')
ImportError: transactions data requires pandas
```

**Comment by mplewis** [comment]
You need to install the Pandas package to access Mint transactions. Try running `pip install pandas` first.

**Comment by mrooney** [comment]
Thanks, I added a more helpful error message for 1.10, how's this? "transactions data requires pandas; please pip install pandas"
