### ISSUE TITLE
model WebAppInstallationPromo failed with UkmEngineDisabled

### ISSUE THREAD

**Issue by emann3** [mrooney/mintapi#605]
**Describe the bug**
received error in title

What version of MintAPI are you using? 2.12
What command[s] did you run / steps to reproduce? mintapi -f today --accounts -t --start-date 01/01/2023 --attention <user> <pass>
Stacktrace/error received:
DevTools listening on ws://127.0.0.1:52926/devtools/browser/157df0d7-7de7-4e16-96b7-24df0c080933
[238104:237836:0725/101159.423:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[238104:237836:0725/101159.431:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[238104:237836:0725/101159.431:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[238104:237836:0725/101200.111:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[238104:237836:0725/101200.146:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[238104:237836:0725/101200.146:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[238088:237696:0725/101202.832:ERROR:device_event_log_impl.cc(222)] [10:12:02.833] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
**[238088:237696:0725/101202.943:ERROR:feature_processor_state.cc(39)] Processing error occured: model WebAppInstallationPromo failed with UkmEngineDisabled, message:
Message:
Stacktrace:
Backtrace:**
        GetHandleVerifier [0x0037A813+48355]
        (No symbol) [0x0030C4B1]
        (No symbol) [0x00215358]
        (No symbol) [0x002409A5]
        (No symbol) [0x00240B3B]
        (No symbol) [0x0026E232]
        (No symbol) [0x0025A784]
        (No symbol) [0x0026C922]
        (No symbol) [0x0025A536]
        (No symbol) [0x002382DC]
        (No symbol) [0x002393DD]
        GetHandleVerifier [0x005DAABD+2539405]
        GetHandleVerifier [0x0061A78F+2800735]
        GetHandleVerifier [0x0061456C+2775612]
        GetHandleVerifier [0x004051E0+616112]
        (No symbol) [0x00315F8C]
        (No symbol) [0x00312328]
        (No symbol) [0x0031240B]
        (No symbol) [0x00304FF7]
        BaseThreadInitThunk [0x763100C9+25]
        RtlGetAppContainerNamedObjectPath [0x772F7B1E+286]
        RtlGetAppContainerNamedObjectPath [0x772F7AEE+238]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 197, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 351, in sign_in
    WebDriverWait(driver, 20).until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0037A813+48355]
        (No symbol) [0x0030C4B1]
        (No symbol) [0x00215358]
        (No symbol) [0x002409A5]
        (No symbol) [0x00240B3B]
        (No symbol) [0x0026E232]
        (No symbol) [0x0025A784]
        (No symbol) [0x0026C922]
        (No symbol) [0x0025A536]
        (No symbol) [0x002382DC]
        (No symbol) [0x002393DD]
        GetHandleVerifier [0x005DAABD+2539405]
        GetHandleVerifier [0x0061A78F+2800735]
        GetHandleVerifier [0x0061456C+2775612]
        GetHandleVerifier [0x004051E0+616112]
        (No symbol) [0x00315F8C]
        (No symbol) [0x00312328]
        (No symbol) [0x0031240B]
        (No symbol) [0x00304FF7]
        BaseThreadInitThunk [0x763100C9+25]
        RtlGetAppContainerNamedObjectPath [0x772F7B1E+286]
        RtlGetAppContainerNamedObjectPath [0x772F7AEE+238]

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 197, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 351, in sign_in
    WebDriverWait(driver, 20).until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0037A813+48355]
        (No symbol) [0x0030C4B1]
        (No symbol) [0x00215358]
        (No symbol) [0x002409A5]
        (No symbol) [0x00240B3B]
        (No symbol) [0x0026E232]
        (No symbol) [0x0025A784]
        (No symbol) [0x0026C922]
        (No symbol) [0x0025A536]
        (No symbol) [0x002382DC]
        (No symbol) [0x002393DD]
        GetHandleVerifier [0x005DAABD+2539405]
        GetHandleVerifier [0x0061A78F+2800735]
        GetHandleVerifier [0x0061456C+2775612]
        GetHandleVerifier [0x004051E0+616112]
        (No symbol) [0x00315F8C]
        (No symbol) [0x00312328]
        (No symbol) [0x0031240B]
        (No symbol) [0x00304FF7]
        BaseThreadInitThunk [0x763100C9+25]
        RtlGetAppContainerNamedObjectPath [0x772F7B1E+286]
        RtlGetAppContainerNamedObjectPath [0x772F7AEE+238]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\Scripts\mintapi-script.py", line 33, in <module>
    sys.exit(load_entry_point('mintapi==2.12', 'console_scripts', 'mintapi')())
  File "C:\Python310\lib\site-packages\mintapi\cli.py", line 465, in main
    mint = Mint(
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 124, in __init__
    self.login_and_get_token(
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 220, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/app/sign-in?app_group=Mint&asset_alias=Intuit.ifs.mint&namespace_id=50000026&redirect_uri=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D9b61c38f-8ba7-49ca-9478-ff8a00a7bc2c

**What did you expect to happen?**
get transactions, accounts, and attention

**What actually happened?**
**error/stacktrace, chrome does not get past mint login page (does not select userID)**

**Additional context**
This worked yesterday, after it failed today, i loaded the latest chrome and it still fails (115.0.5790.102)

**Comment by dantheman84** [comment]
Having this exact same issue as well, updated to latest chrome as well (115.0.5790.102)

**Comment by pdeangelo** [comment]
I might have a different mint version than you.  I am getting the error here in signin
WebDriverWait(driver, 20).until(
        expected_conditions.presence_of_element_located(
            (
                By.CSS_SELECTOR,
                "#ius-link-use-a-different-id-known-device, #ius-userid, #ius-identifier, #ius-option-username,.ius-hosted-ui-main-container"
            )
        )
    )

**Comment by pdeangelo** [comment]
I changed it to this and it worked:
 WebDriverWait(driver, 20).until(
        expected_conditions.presence_of_element_located(
            (
                By.CSS_SELECTOR,
                "#ius-link-use-a-different-id-known-device, #ius-userid, #ius-identifier, #ius-option-username,.ius-hosted-ui-main-container,#iux-identifier-first-unknown-identifier"
            )
        )
    )

**Comment by gyllen** [comment]
Sorry that I am to lazy to provide a real diff here :/, anyway here is line 351-360

```
    WebDriverWait(driver, 20).until(
        expected_conditions.presence_of_element_located(
            (
                By.CSS_SELECTOR,
                ".ius-hosted-ui-main-container, #ius-link-use-a-different-id-known-device, #ius-userid, "
                # '#ius-identifier, #ius-option-username, [data-testid="IdentifierFirstSubmitButton"]',
                '#ius-identifier, #ius-option-username, [data-testid="AccountChoiceIdentifier_0"]',
            )
        )
    )
```

**Comment by mrooney** [comment]
Would someone be willing to make a PR which includes the old and new selectors?
