### ISSUE TITLE
TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#87]
I am getting the title's error when trying to get accounts (after successfully connecting).  Any suggestions?

Its happening in api.py at line 249:
`            accounts = self.populate_extended_account_detail(accounts)
`

**Comment by jorythompson** [comment]
Nevermind - it gives me the error when I take out the sleep also.

**Comment by jorythompson** [comment]
Here is another (probably similar) issue.
1.  I logged into mint and got the two cookies on a windows machine
2.  I ran my app and it worked fine
3.  I used the same configuration and app and tried running from another (headless, and hence the reason I cannot access Mint from it) Linux machine and got this error:

`
File "mintCheck.py", line 61, in _get_data                                                                                                
    start_date=start_date.strftime('%m/%d/%y')), self.logger)                                                                               
  File "/usr/local/lib/python2.7/dist-packages/mintapi/api.py", line 328, in get_transactions_json                                          
    df = pd.DataFrame(txns)                                                                                                                 
AttributeError: 'NoneType' object has no attribute 'DataFrame'                                                                              
2016-12-04 12:50:57,641:CRITICAL: Traceback (most recent call last):                                                                        
                                                                                                                                            
2016-12-04 12:50:57,642:CRITICAL:   File "mintCheck.py", line 154, in main                                                                  
    mint_check.collect_and_send()                                                                                                           
                                                                                                                                            
2016-12-04 12:50:57,642:CRITICAL:   File "mintCheck.py", line 118, in collect_and_send                                                      
    self._get_data(start_date)                                                                                                              
                                                                                                                                            
2016-12-04 12:50:57,643:CRITICAL:   File "mintCheck.py", line 61, in _get_data                                                              
    start_date=start_date.strftime('%m/%d/%y')), self.logger)                                                                               
                                                                                                                                            
2016-12-04 12:50:57,644:CRITICAL:   File "/usr/local/lib/python2.7/dist-packages/mintapi/api.py", line 328, in get_transactions_json        
    df = pd.DataFrame(txns)                                                                                                                 
                                                                                                                                            
2016-12-04 12:50:57,644:CRITICAL: AttributeError: 'NoneType' object has no attribute 'DataFrame'          `

Line 61 is:
`                mint.get_transactions_json(include_investment=False, skip_duplicates=self.config.mint_remove_duplicates,
                                           start_date=start_date.strftime('%m/%d/%y')), self.logger)
`

Note this occurs after mintapi has already logged in!

Any suggestions would be most welcome.

**Comment by jorythompson** [comment]
Getting TooManyRedirects problem again:
`File "c:\Python27\lib\site-packages\mintapi\api.py", line 254, in get_accounts accounts = self.populate_extended_account_detail(accounts) 
File "c:\Python27\lib\site-packages\mintapi\api.py", line 443, in populate_extended_account_detail response = json.loads(self.get(list_txn_url, headers=headers).text) 
File "c:\Python27\lib\site-packages\requests\sessions.py", line 501, in get return self.request('GET', url, **kwargs) 
File "c:\Python27\lib\site-packages\requests\sessions.py", line 488, in request resp = self.send(prep, **send_kwargs) 
File "c:\Python27\lib\site-packages\requests\sessions.py", line 630, in send history = [resp for resp in gen] if allow_redirects else [] 
File "c:\Python27\lib\site-packages\requests\sessions.py", line 111, in resolve_redirects raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp) 
TooManyRedirects: Exceeded 30 redirects. `

**Comment by mrooney** [comment]
I haven't had any other reports of this, so I'm not sure what to make of it. Are you behind any kind of proxy?

**Comment by jorythompson** [comment]
This problem comes and goes for me.  It was working for months and now this error is back.  I have found if I keep trying, it usually goes away.  Unfortunately I cannot get it to go away this time.

**Comment by jprouty** [comment]
I'm getting this error as well. I have a suspicion that this may be Mint rate limiting the client...

My app runs a pretty tight loop on updating mint transactions and it seems after about ~100 requests I'm running into this error! I'm going to play with rate limiting on my end to try to address the issue.

**Comment by jprouty** [comment]
The interesting thing: get_transactions_json is still running fine (returning about 3 requests worth or 250 transactions). It's only my POSTs that are failing.

**Comment by jprouty** [comment]
Turns out my issue was due to invalid content in the POST request. Specifically, some of my strings I was sending (as the merchant field in a transaction) contained non-ascii characters e.g. '\xc2'

Removing these fixed the problematic requests.

**Comment by mrooney** [comment]
Okay thanks, I'll close this for now then!
